- name : Execute patches - Windows
  #hosts: localhost
  hosts: all
  gather_facts: no
  become: false
  #connection: remote
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Install hotfix validating KB
      win_hotfix:
        hotfix_kb: KB5012666
        source: C:\Updates\windows8-rt-kb5012666-x64_5caa5c0dc4bee0969e2c15114a397c74aa5a239a.msu
        state: present
      register: hotfix_install
    - win_reboot:
      when: hotfix_install.reboot_required
